repos:
  - repo: local
    hooks:
      - id: biome-check
        name: biome check
        entry: npx biome check --write --no-errors-on-unmatched
        language: system
        types_or: [ts, tsx, javascript, jsx, json, css]
        pass_filenames: true
